language: php

php:
  - 5.5
  - 5.6
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  - ./vendor/bin/phpcs phpcs.conf.dist
  - ./vendor/bin/phpmd src/ text codesize,unusedcode,naming,phpmd.xml.dist
  - ./vendor/bin/phpunit
